// Required by Webpack - do not touch
require.context('../', true, /\.(html|json|txt|dat)$/i)
require.context('../images/', true, /\.(gif|jpg|png|svg|eot|ttf|woff|woff2)$/i)
require.context('../stylesheets/', true, /\.(css|scss)$/i)

// First: Set up your name
let std_name = "Joseph Brower"
document.querySelector('#std_name').innerHTML = `<strong>${std_name}</strong>`

//Then: comes everything else
//import * as d3 from "d3";

import * as d3 from "d3";

// <svg width="500" height="600" style="background: rgb(232, 207, 207)" fill="transparent">d3.select('main')
let SvgAnt = d3.select('main').append('svg')
    .attr('width', 200)
    .attr('height', 200)
    .style('background', '#fff')
    .style('fill', 'transparent')
let SvgTree = d3.select('main').append('svg')
    .attr('width', 200)
    .attr('height', 200)
    .style('background', '#fff')
    .style('fill', 'transparent')
let SvgShape = d3.select('main').append('svg')
    .attr('width', 200)
    .attr('height', 200)
    .style('background', '#fff')
    .style('fill', 'transparent')
let SvgDiode = d3.select('main').append('svg')
    .attr('width', 200)
    .attr('height', 200)
    .style('background', '#fff')
    .style('fill', 'transparent')
let SvgCircle = d3.select('main').append('svg')
    .attr('width', 200)
    .attr('height', 200)
    .style('background', '#fff')
    .style('fill', 'transparent')
function DrawAnt() {
    let bob = 15;
    let leg1 = SvgAnt.append('line')
        .attr('x1', 35 + bob)
        .attr('y1', 50 + bob)
        .attr('x2', 172 - bob)
        .attr('y2', 150 - bob)
        .attr('stroke', 'grey')
        .attr('fill', 'grey')
        .style('stroke-width', 2);
    let leg2 = SvgAnt.append('line')
        .attr('x1', 172 - bob)
        .attr('y1', 50 + bob)
        .attr('x2', 35 + bob)
        .attr('y2', 150 - bob)
        .attr('stroke', 'grey')
        .attr('fill', 'grey')
        .style('stroke-width', 2);
    let leg3 = SvgAnt.append('line')
        .attr('x1', 65 + bob)
        .attr('y1', 30 + bob)
        .attr('x2', 142 - bob)
        .attr('y2', 170 - bob)
        .attr('stroke', 'grey')
        .attr('fill', 'grey')
        .style('stroke-width', 2);
    let leg4 = SvgAnt.append('line')
        .attr('x1', 142 - bob)
        .attr('y1', 30 + bob)
        .attr('x2', 65 + bob)
        .attr('y2', 170 - bob)
        .attr('stroke', 'grey')
        .attr('fill', 'grey')
        .style('stroke-width', 2);
    let abdomen = SvgAnt.append('ellipse')
        .attr('cx', 150)
        .attr('cy', 100)
        .attr('rx', 30)
        .attr('ry', 16 + 5)
        .attr('stroke', 'black')
        .attr('fill', 'black')
    let thorax = SvgAnt.append('ellipse')
        .attr('cx', 105)
        .attr('cy', 100)
        .attr('rx', 25)
        .attr('ry', 10)
        .attr('stroke', 'black')
        .attr('fill', 'black')

    let head = SvgAnt.append('ellipse')
        .attr('cx', 70)
        .attr('cy', 100)
        .attr('rx', 20)
        .attr('ry', 15)
        .attr('stroke', 'black')
        .attr('fill', 'black')

}
function DrawTree(){
    let trunk = SvgTree.append('rect')
        .attr('x', 88)
        .attr('y', 50)
        .attr('width', 20)
        .attr('height', 150)
        .attr('stroke', 'brown')
        .attr('fill', 'brown')
    let tree1 = SvgTree.append("path")
        .style("stroke", "green")
        .style('fill', 'green')
        .style('stroke-width', 3)
        .attr("d", "M25,150 L175,150 L120,100 L150,100 L120,50 z")

    let tree2 = SvgTree.append("path")
        .style("stroke", "green")
        .style('fill', 'green')
        .style('stroke-width', 3)
        .attr("d", "M130,60 L70,60 L100,30 z")
}
function DrawShape(){
    let shape1 = SvgShape.append("path")
        .style("stroke", "blue")
        .style('fill', 'blue')
        .style('stroke-width', 3)
        .attr("d", "M40,40 L160,40 L160, 130, Q160,150 140,150 L60,150 Q40,150 40,130z")
    let shape2 = SvgShape.append('path')
        .style("stroke", "lightblue")
        .style('fill', 'lightblue')
        .style('stroke-width', 2)
        .attr("d", "M60,50 L60,15 L70,15 L70,50 Q65,55 60,50")
    let shape3 = SvgShape.append('path')
        .style("stroke", "lightblue")
        .style('fill', 'lightblue')
        .style('stroke-width', 2)
        .attr("d", "M130,50 L130,15 L140,15 L140,50 Q135,55 130,50")
    let shape4 = SvgShape.append('rect')
        .attr('x', 71)
        .attr('y', 15)
        .attr('width', 58)
        .attr('height', 10)
        .attr("stroke", "steelblue")
        .attr("fill", "steelblue")
    let shape5 = SvgShape.append('circle')
        .attr('cx', 80)
        .attr('cy', 100)
        .attr('r', 20)
        .attr('stroke', 'red')
        .attr('fill', 'red')
    let shape6 = SvgShape.append('circle')
        .attr('cx', 100)
        .attr('cy', 70)
        .attr('r', 20)
        .attr('stroke', 'green')
        .attr('fill', 'green')
    let shape7 = SvgShape.append('circle')
        .attr('cx', 120)
        .attr('cy', 120)
        .attr('r', 20)
        .attr('stroke', 'yellow')
        .attr('fill', 'yellow')
}
function DrawDiode(){
    let line1 = SvgDiode.append("path")
        .style("stroke", "black")
        .style('fill', 'none')
        .style('stroke-width', 3)
        .attr("d", "M20,100 L180,100 ")
    let triangle1 = SvgDiode.append("path")
        .style("stroke", "black")
        .style('fill', 'none')
        .style('stroke-width', 3)
        .attr("d", "M75,75 L125,100 L75,125z")
    let line2 = SvgDiode.append("path")
        .style("stroke", "black")
        .style('fill', 'none')
        .style('stroke-width', 3)
        .attr("d", "M125,75 L125,125 ")
    let circle1 = SvgDiode.append('circle')
        .attr('cx', 100)
        .attr('cy', 100)
        .attr('r', 45)
        .attr('stroke-width', 3)
        .attr('stroke', 'black')
        .attr('fill', 'none')
}
function DrawCircle(){
    let triangle1 = SvgCircle.append("polygon")
        .style("stroke", "gold")
        .style('fill', 'gold')
        .style('stroke-width', 2)
        .attr("points", "100,40 80,70 90,70 100,55 110,70 120,70")
    let triangle2 = SvgCircle.append("polygon")
        .style("stroke", "black")
        .style('fill', 'black')
        .style('stroke-width', 2)
        .attr("points", '125,77.5 155,122.5 45,122.5 75,77.5')
    let line1 = SvgCircle.append("polygon")
        .style("stroke", "white")
        .style('fill', 'transparent')
        .style('stroke-width', 5)
        .attr("points", '120,73 0,140')
    let line2 = SvgCircle.append("polygon")
        .style("stroke", "white")
        .style('fill', 'transparent')
        .style('stroke-width', 5)
        .attr("points", '88,73 150,140')

}
DrawAnt();
DrawTree();
DrawShape();
DrawDiode();
DrawCircle();

SvgAnt.transition().attr('transform', 'scale(.25)').duration(2000)
SvgTree.transition().attr('transform', 'translate(100, 200)').duration(2000).delay(2000)
SvgTree.transition().attr('transform', 'translate(-200, 200)').duration(2000).delay(4000)
SvgShape.transition().attr('transform', 'translate(0, 200)').duration(1000).delay(6000)
SvgCircle.transition().attr('transform', 'translate(0, -200)').duration(2000).delay(8000)
SvgCircle.transition().attr('transform', 'translate(-400, -200)').duration(500).delay(10000)
SvgCircle.transition().attr('transform', 'translate(-400, 0)').duration(2000).delay(10500)
SvgDiode.transition().attr('transform', 'rotate(180)').duration(12500)